502:
	gcc -c src/asm502.c -o obj/asm502.o -I./inc
	gcc obj/asm502.o -o bin/exam
	./bin/exam
503:
	gcc -c src/asm503.c -o obj/asm503.o -I./inc
	gcc obj/asm503.o -o bin/exam
	./bin/exam
504:
	gcc -c src/asm504.c -o obj/asm504.o -I./inc
	gcc obj/asm504.o -o bin/exam
	./bin/exam
link:
	gcc obj/asm501.o -o bin/exam

all: 
	gcc -c src/asm501.c -o obj/asm501.o -I./inc


clean:
	rm -rf obj/* bin/* 
	
